[package]
name = "c3d-rs"
version = "0.1.0"
authors = ["Raymond Yeh <extraymond@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.19"
log = "0.4.8"
femme = "2.1.0"
anyhow = "1.0.31"
